application: johnandjuliagetmarried
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: .*
  script: main.py
builtins:
- datastore_admin: on
- remote_api: on
